name = "CutCellHeat"
uuid = "1b1ac804-37a6-46ce-8e96-22c73b48a453"
authors = ["Fastaxx <Fastaxx@github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CutCellMesh = "24df4ea3-ebf2-4a26-8fd2-c05fb361f768"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
